parameters:
    success_relation_manager: %success_relation.manager%
    success_relation_class: %success_relation.class%
    success_relation_twig: Success\RelationBundle\Twig\Extension\RelationExtension

services:
    success.relation.entity_manager:
        alias: doctrine.orm.default_entity_manager

    success.relation.manager:
        class: %success_relation_manager%
        arguments: ['@success.relation.entity_manager', %success_relation_class%, '@event_dispatcher']

    success.relation.twig:
        class: %success_relation_twig%
        arguments: ['@success.relation.manager']
        tags:
            - { name: twig.extension }
